### ISSUE TITLE
more-info pops up on icon click

### ISSUE THREAD

**Issue by kineticscreen** [piitaya/lovelace-climate-mode-entity-row#11]
Since the update to 2021.12 tapping on the mode icons also results in the more-info panel opening.

**Comment by piitaya** [comment]
Thanks for the bug reporting, it should be fixed in the new version 🙂

**Comment by kineticscreen** [comment]
I think this may have fixed it for desktop, but not for the mobile apps. This is the same thing that happened with 'multiple entity rows' problem and first fix for this.
https://github.com/benct/lovelace-multiple-entity-row/issues/217

**Comment by NickM-27** [comment]
@kineticscreen @piitaya The "mobile" fix will come in a HomeAssistant frontend update as there was an issue. You can see that issue here: https://github.com/home-assistant/frontend/issues/10961#issuecomment-997370789

**Comment by piitaya** [comment]
@NickM-27 @kineticscreen I push a fix in version 1.3.3 (the same fix used in `multiple-entity-row`).
It requires the last HA version `2021.12.4`. It works for me. Don't hesitate to tell me if you have any issue with this 🙂

**Comment by kineticscreen** [comment]
Seems to be working perfectly!
