### ISSUE TITLE
Hvac_mode cool no icon

### ISSUE THREAD

**Issue by Dutchy-79** [piitaya/lovelace-climate-mode-entity-row#15]
I tried the card and it won't show the cool icon
![Screenshot_20220626-210255_Home Assistant](https://user-images.githubusercontent.com/22749572/175830072-3c21279f-5029-40ee-8329-2e9b77152fe7.png)
![Screenshot_20220626-210315_Home Assistant](https://user-images.githubusercontent.com/22749572/175830073-ec512056-0647-4cea-874f-633081d85559.png)
![Screenshot_20220626-210526_Home Assistant](https://user-images.githubusercontent.com/22749572/175830074-5cff3d40-6c66-4f83-8f09-e4374163118f.png)

**Comment by piitaya** [comment]
I added the default icon. Don't hesitate to customize the icon using the icon option 🙂

**Comment by Dutchy-79** [comment]
Thanks, I'm still learning so didn't know how. I'll have a look at it. Thanks for the reply.
