### ISSUE TITLE
Request: hide entity icon

### ISSUE THREAD

**Issue by tanker11** [piitaya/lovelace-climate-mode-entity-row#17]
Hello,

I really love this project, it can provide a very compact view of the thermostat/AC control while keeping all the necessary controls on the card.
I have however one issue with the compactness: when a card is very busy with icons, the entity icon (first in the row) is using up too much space. Would it be possible to hide it, just like the entity name?

Sorry if I missed it, but could not figure out from the descriptions.

**Comment by piitaya** [comment]
This card is a row for [entities card](https://www.home-assistant.io/dashboards/entities/). As you can see, each row have a icon so we can not disable it to keep consistency with other row.
