### ISSUE TITLE
No more color icon by default

### ISSUE THREAD

**Issue by plouf34** [piitaya/lovelace-climate-mode-entity-row#9]
Hello
Since the last update, there is no more icon color by default?
Regards

**Comment by piitaya** [comment]
Last HA update or last update of this addon? I will look into it 🙂

**Comment by SVH-Powel** [comment]
I could not get colors either. I also added specific color configuration, but still no color. It works in 110

`entities:
  - entity: climate.stue_og_kjokken
    type: custom:climate-mode-entity-row
    modes:
      - hvac_mode: 'off'
        color: RoyalBlue
      - preset_mode: away
        color: RoyalBlue
      - preset_mode: eco
        icon: mdi:weather-night
        color: MediumAquamarine
      - preset_mode: comfort
        color: Salmon
        icon: mdi:radiator
  - entity: climate.hagestue
    type: custom:climate-mode-entity-row
    modes:
      - hvac_mode: 'off'
        color: RoyalBlue
      - preset_mode: away
        color: RoyalBlue
      - preset_mode: eco
        icon: mdi:weather-night
        color: MediumAquamarine
      - preset_mode: comfort
        color: Salmon
        icon: mdi:radiator`
